### ISSUE TITLE
test failures with Rust 1.75+ when running in `--release` mode

### ISSUE THREAD

**Issue by decathorpe** [starkat99/half-rs#103]
We're running the `half` crate's tests during our package builds in Fedora Linux and our CI has detected that since the update to Rust 1.75.0, some tests have started to fail - but only when run in `--release` mode:

```
failures:
---- bfloat::test::test_nan_conversion_to_larger stdout ----
thread 'bfloat::test::test_nan_conversion_to_larger' panicked at src/bfloat.rs:1531:9:
assertion failed: neg_nan64_from_32.is_nan() && neg_nan64_from_32.is_sign_negative()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- bfloat::test::test_nan_conversion_to_smaller stdout ----
thread 'bfloat::test::test_nan_conversion_to_smaller' panicked at src/bfloat.rs:1502:9:
assertion failed: neg_nan32_from_64.is_nan() && neg_nan32_from_64.is_sign_negative()
---- binary16::test::test_nan_conversion_to_larger stdout ----
thread 'binary16::test::test_nan_conversion_to_larger' panicked at src/binary16.rs:1599:9:
assertion failed: neg_nan64_from_32.is_nan() && neg_nan64_from_32.is_sign_negative()
---- binary16::test::test_nan_conversion_to_smaller stdout ----
thread 'binary16::test::test_nan_conversion_to_smaller' panicked at src/binary16.rs:1570:9:
assertion failed: neg_nan32_from_64.is_nan() && neg_nan32_from_64.is_sign_negative()
failures:
    bfloat::test::test_nan_conversion_to_larger
    bfloat::test::test_nan_conversion_to_smaller
    binary16::test::test_nan_conversion_to_larger
    binary16::test::test_nan_conversion_to_smaller
```

**Comment by decathorpe** [comment]
Two of these failures are also reproducible with miri (`cargo +nightly miri test`) if that helps:

```
failures:

---- bfloat::test::test_nan_conversion_to_smaller stdout ----
thread 'bfloat::test::test_nan_conversion_to_smaller' panicked at src/bfloat.rs:1501:9:
assertion failed: nan32_from_64.is_nan() && nan32_from_64.is_sign_positive()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- binary16::test::test_nan_conversion_to_smaller stdout ----
thread 'binary16::test::test_nan_conversion_to_smaller' panicked at src/binary16.rs:1569:9:
assertion failed: nan32_from_64.is_nan() && nan32_from_64.is_sign_positive()


failures:
    bfloat::test::test_nan_conversion_to_smaller
    binary16::test::test_nan_conversion_to_smaller
```

**Comment by starkat99** [comment]
It appears something changed in how Rust performs float casts of NaN. The line the fails is casting a NaN f64 as f32. I'm going to remove the f64/f32 cast check as they're not necessary as we only need to be testing f16 conversions, but it looks like a compiler bug I'm going to submit.

**Comment by starkat99** [comment]
Opened a bug with compiler: https://github.com/rust-lang/rust/issues/120898

**Comment by decathorpe** [comment]
Thank you for investigating!
