### ISSUE TITLE
test failures on risv64.

### ISSUE THREAD

**Issue by plugwash** [starkat99/half-rs#113]
On Debian's CI infrastructure we are seeing test failures on riscv64
 
https://ci.debian.net/packages/r/rust-half/testing/riscv64/51293727/#S6

    1037s ---- bfloat::test::test_nan_conversion_to_larger stdout ----
    1037s thread 'bfloat::test::test_nan_conversion_to_larger' panicked at src/bfloat.rs:1246:9:
    1037s assertion failed: neg_nan64_from_32.is_nan() && neg_nan64_from_32.is_sign_negative()
    1037s stack backtrace:
    1037s    0: rust_begin_unwind
    1037s              at /usr/src/rustc-1.79.0/library/std/src/panicking.rs:652:5
    1037s    1: core::panicking::panic_fmt
    1037s              at /usr/src/rustc-1.79.0/library/core/src/panicking.rs:72:14
    1037s    2: core::panicking::panic
    1037s              at /usr/src/rustc-1.79.0/library/core/src/panicking.rs:146:5
    1037s    3: half::bfloat::test::test_nan_conversion_to_larger
    1037s              at ./src/bfloat.rs:1246:9
    1037s    4: half::bfloat::test::test_nan_conversion_to_larger::{{closure}}
    1037s              at ./src/bfloat.rs:1225:39
    1037s    5: core::ops::function::FnOnce::call_once
    1037s              at /usr/src/rustc-1.79.0/library/core/src/ops/function.rs:250:5
    1037s    6: core::ops::function::FnOnce::call_once
    1037s              at /usr/src/rustc-1.79.0/library/core/src/ops/function.rs:250:5
    1037s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    1037s 
    1037s ---- bfloat::test::test_nan_conversion_to_smaller stdout ----
    1037s thread 'bfloat::test::test_nan_conversion_to_smaller' panicked at src/bfloat.rs:1217:9:
    1037s assertion failed: neg_nan32_from_64.is_nan() && neg_nan32_from_64.is_sign_negative()
    1037s stack backtrace:
    1037s    0: rust_begin_unwind
    1037s              at /usr/src/rustc-1.79.0/library/std/src/panicking.rs:652:5
    1037s    1: core::panicking::panic_fmt
    1037s              at /usr/src/rustc-1.79.0/library/core/src/panicking.rs:72:14
    1037s    2: core::panicking::panic
    1037s              at /usr/src/rustc-1.79.0/library/core/src/panicking.rs:146:5
    1037s    3: half::bfloat::test::test_nan_conversion_to_smaller
    1037s              at ./src/bfloat.rs:1217:9
    1037s    4: half::bfloat::test::test_nan_conversion_to_smaller::{{closure}}
    1037s              at ./src/bfloat.rs:1200:40
    1037s    5: core::ops::function::FnOnce::call_once
    1037s              at /usr/src/rustc-1.79.0/library/core/src/ops/function.rs:250:5
    1037s    6: core::ops::function::FnOnce::call_once
    1037s              at /usr/src/rustc-1.79.0/library/core/src/ops/function.rs:250:5
    1037s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    1037s 
    1037s ---- binary16::test::test_nan_conversion_to_larger stdout ----
    1037s thread 'binary16::test::test_nan_conversion_to_larger' panicked at src/binary16.rs:1399:9:
    1037s assertion failed: neg_nan64_from_32.is_nan() && neg_nan64_from_32.is_sign_negative()
    1037s stack backtrace:
    1037s    0: rust_begin_unwind
    1037s              at /usr/src/rustc-1.79.0/library/std/src/panicking.rs:652:5
    1037s    1: core::panicking::panic_fmt
    1037s              at /usr/src/rustc-1.79.0/library/core/src/panicking.rs:72:14
    1037s    2: core::panicking::panic
    1037s              at /usr/src/rustc-1.79.0/library/core/src/panicking.rs:146:5
    1037s    3: half::binary16::test::test_nan_conversion_to_larger
    1037s              at ./src/binary16.rs:1399:9
    1037s    4: half::binary16::test::test_nan_conversion_to_larger::{{closure}}
    1037s              at ./src/binary16.rs:1378:39
    1037s    5: core::ops::function::FnOnce::call_once
    1037s              at /usr/src/rustc-1.79.0/library/core/src/ops/function.rs:250:5
    1037s    6: core::ops::function::FnOnce::call_once
    1037s              at /usr/src/rustc-1.79.0/library/core/src/ops/function.rs:250:5
    1037s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    1037s 
    1037s ---- binary16::test::test_nan_conversion_to_smaller stdout ----
    1037s thread 'binary16::test::test_nan_conversion_to_smaller' panicked at src/binary16.rs:1370:9:
    1037s assertion failed: neg_nan32_from_64.is_nan() && neg_nan32_from_64.is_sign_negative()
    1037s stack backtrace:
    1037s    0: rust_begin_unwind
    1037s              at /usr/src/rustc-1.79.0/library/std/src/panicking.rs:652:5
    1037s    1: core::panicking::panic_fmt
    1037s              at /usr/src/rustc-1.79.0/library/core/src/panicking.rs:72:14
    1037s    2: core::panicking::panic
    1037s              at /usr/src/rustc-1.79.0/library/core/src/panicking.rs:146:5
    1037s    3: half::binary16::test::test_nan_conversion_to_smaller
    1037s              at ./src/binary16.rs:1370:9
    1037s    4: half::binary16::test::test_nan_conversion_to_smaller::{{closure}}
    1037s              at ./src/binary16.rs:1353:40
    1037s    5: core::ops::function::FnOnce::call_once
    1037s              at /usr/src/rustc-1.79.0/library/core/src/ops/function.rs:250:5
    1037s    6: core::ops::function::FnOnce::call_once
    1037s              at /usr/src/rustc-1.79.0/library/core/src/ops/function.rs:250:5
    1037s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by plugwash** [comment]
Apologies, I forgot to check were were on the latest version before filing. 

This looks to have been fixed by the fix for https://ci.debian.net/packages/r/rust-half/testing/riscv64/51293727/#S6
